name: data_prep
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'openssl=1.0.2h=2'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'python=2.7.12=1'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=26.1.1=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - backports.weakref==1.0.post1
  - bleach==1.5.0
  - enum34==1.1.6
  - funcsigs==1.0.2
  - futures==3.2.0
  - html5lib==0.9999999
  - keras==2.1.2
  - markdown==2.6.10
  - mock==2.0.0
  - numpy==1.13.3
  - pandas==0.21.0
  - pbr==3.1.1
  - protobuf==3.5.0.post1
  - python-dateutil==2.6.1
  - pytz==2017.3
  - pyyaml==3.12
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - six==1.11.0
  - sklearn-pandas==1.6.0
  - tensorflow==1.4.1
  - tensorflow-tensorboard==0.4.0rc3
  - werkzeug==0.13
prefix: !!python/unicode '/Users/bjherger/anaconda2/envs/data_prep'
